Repository pablosalvador10/gbb-ai-hls-factory-prior-auth, pull requests merged in 2025-02, with the labels that each got.

#48 updating main readme, updated azd_deployment wiki page
  .pre-commit-config.yaml
  README.md
  app/backend/core/config.py
  app/backend/core/constants.py
  app/backend/core/database.py
  app/backend/main.py
  app/backend/users/manager.py
  app/backend/users/schemas.py
  docs/.archive/deployment.md
  docs/CODEOWNERS
  docs/azd_deployment.md
  docs/images/azp_help_containerjoblogs_1.png
  docs/images/azp_help_containerlogs_1.png
  docs/images/azp_help_containerlogs_2.png
  docs/images/azp_help_deployments.png
  infra/README.md
  infra/abbreviations.json
  infra/main.bicep
  infra/main.json
  infra/main.parameters.json
  infra/modules/ai/README.md
  infra/modules/ai/docintelligence.json
  infra/modules/ai/mais.json
  infra/modules/ai/openai.json
  infra/modules/apim-genai/README.md
  infra/modules/compute/README.md
  infra/modules/compute/fetch-container-image.json
  infra/modules/data/README.md
  infra/modules/data/cosmos-mongo-ru.json
  infra/modules/data/cosmos-mongo.json
  infra/modules/data/search.json
  infra/modules/data/storage.json
  infra/resources.bicep
  infra/resources.json
  infra/scripts/README.md
  utils/scripts/README.md
  utils/scripts/cleanup.sh
  utils/scripts/create-application.sh
  utils/scripts/deploy.sh
  utils/scripts/generate-bicep-documentation.ps1
Labels: documentation, enhancement

#55 Fixing CI pipelines, adjusting precommit, fixed azd backend
  .github/workflows/azd_ci.yml
  .github/workflows/azd_deploy.yml
  .github/workflows/main_staging_ci.yml
  .gitignore
  .pre-commit-config.yaml
  02-test-pa-agentic-rag.ipynb
  03-test-pa-e2e.ipynb
  CONTRIBUTING.md
  app/backend/core/exceptions.py
  app/backend/main.py
  app/backend/paprocessing/models.py
  azure.yaml
  docs/.archive/deployment.md
  pyproject.toml
  requirements-codequality.txt
  src/agenticai/agents.py
  src/agenticai/plugins/plugins_store/retrieval/aievaluator.py
  src/agenticai/plugins/plugins_store/retrieval/aisearch.py
  src/agenticai/skills.py
  src/aoai/aoai_helper.py
  src/aoai/tokenizer.py
  src/documentintelligence/document_intelligence_helper.py
  src/extractors/blob_data_extractor.py
  src/ocr/document_intelligence.py
  src/pipeline/agenticRag/evals.py
  src/pipeline/agenticRag/run.py
  src/pipeline/autoDetermination/run.py
  src/pipeline/paprocessing/evals.py
  src/pipeline/policyIndexer/run.py
Labels: enhancement

#60 [meta] README.md hygeine
  CONTRIBUTING.md
  README.md
Labels: documentation, meta
